### ISSUE TITLE
[Feature Req] Scan crash reports for common problems and post possible solutions

### ISSUE THREAD

**Issue by calloatti** [FabricMC/fabric-discord-bot#1]
Scan crash reports posted in #player-support for common problems and post possible solutions

Something similar to what is used over at the MultiMC Discord

![image](https://user-images.githubusercontent.com/12817862/86063420-36029180-ba41-11ea-9976-fde1d32ae1e7.png)

**Comment by Ueaj-Kerman** [comment]
yes

**Comment by Scotsguy** [comment]
https://github.com/Scotsguy/background-cat/tree/async
^ The source for background cat, it's Rust (with an old python version, also) and a lot of regex

**Comment by Scotsguy** [comment]
Fixed by #2
