### ISSUE TITLE
Tags (Tricks) system

### ISSUE THREAD

**Issue by gdude2002** [FabricMC/fabric-discord-bot#15]
This will replace K9's tricks system once implemented. The idea is to have something similar, with the following design:

* Tags will be stored [on Git only](https://github.com/FabricMC/community), and the bot will maintain a local copy of the repo
* As tags should be able to generate embeds, we've come up with a simple format: Markdown with YAML front matter. This won't actually be front matter in the strictest sense - it'll contain everything about the tag aside from the actual main content itself, including embed fields and colours.
* Add some additional parsing - for example, `{Role:MODERATORS}` to insert a role mention.
* Multiple tag types - `text`, `embed` and `alias`

This will involve writing some library-style code, but it should be possible to write a tag linter into the bot as well, so that the JAR could be downloaded by the CI system and used to lint the tags in the repo. We'll see, though.

**Comment by Scotsguy** [comment]
Done in #18 and FabricMC/community#2 🦞
