### ISSUE TITLE
?slowmode is but an illusion

### ISSUE THREAD

**Issue by Arc-blroth** [FabricMC/fabric-discord-bot#16]
It appears that the ?slowmode function does not actually set slowmode on the channel (see [ModeratorExtension.kt](https://github.com/FabricMC/fabric-discord-bot/blob/rewrite/src/main/kotlin/net/fabricmc/bot/extensions/ModerationExtension.kt#L312))
This should probably be fixed as soon as possible, to help moderators do their job :)

**Comment by i509VCB** [comment]
Illusion: 100

**Comment by gdude2002** [comment]
We are all slowmode.
