### ISSUE TITLE
Mappings Command does not give intermediary names as the first suggestion when searching for a number

### ISSUE THREAD

**Issue by OverlordsIII** [FabricMC/fabric-discord-bot#24]
This is not really a big issue, but when you run something like `?ym 4964` the bot doesn't actually look for `?ym method_4964` and looks for something else instead. An example that probably makes more sense is in the picture below. Thought this might be a nice feature so you wouldn't need to type out method_ or class_ .
![image](https://user-images.githubusercontent.com/69648849/100290740-e9a87880-2f30-11eb-82c5-b7660273bd7d.png)

Edit: Looks like the bot *does* pick it up, but displays it on the very last page, could it just be moved to the first page?

**Comment by i509VCB** [comment]
I have a PR resolving the 20 -> method_20 lookup for methods and fields. The class lookup will probably be a future PR.

**Comment by Scotsguy** [comment]
Fixed in #25
