### ISSUE TITLE
Modlog messages should include user name verbatim

### ISSUE THREAD

**Issue by dblsaiko** [FabricMC/fabric-discord-bot#32]
Entries like "<@227459273100230656> has been muted..." aren't very useful to look at if the discord client doesn't load the username. I'd suggest changing it to send e.g. "2xsaiko#0001 (<@227459273100230656>) has been muted..." for better readability.

**Comment by gdude2002** [comment]
https://github.com/FabricMC/fabric-discord-bot/blob/kord-0.7/src/main/kotlin/net/fabricmc/bot/utils/UserUtils.kt#L13
