### ISSUE TITLE
Track and reapply certain roles when a user leaves the server and later rejoins.

### ISSUE THREAD

**Issue by i509VCB** [FabricMC/fabric-discord-bot#5]
This would help avoid cases such as users just leaving and rejoining to remove their own `Muted` or `No Support` roles. May also be useful for some management roles or tracking `The Inquisition`.

**Comment by Scotsguy** [comment]
Infraction-related roles (mutes) get reapplied when a user joins now.
Code reference: https://github.com/FabricMC/fabric-discord-bot/blob/176e311346b186eb1761d13ded0320e4cc45b941/src/main/kotlin/net/fabricmc/bot/extensions/SyncExtension.kt#L203-L216
