### ISSUE TITLE
Add ability to toggle slowmode option on channels via commands

### ISSUE THREAD

**Issue by i509VCB** [FabricMC/fabric-discord-bot#6]
Since toggling slowmode on a channel requires the ability to completely modify or remove a channel, I feel a command should exist to toggle slowmode for a channel.

Was thinking of a syntax like this:

`!slowmode <#channel> <time>|<off>`

For example, `!slowmode #general 30s` would enable slowmode of 30s on #general. While `!slowmode #general off` would disable slowmode on #general

The time would be the valid time increments support by discord for the channel's slowmode and the `off` literal would disable slowmode on the channel.

**Comment by Scotsguy** [comment]
Bots can set slowmode to any number of integer seconds between 0 and 21600 (6 hours)
